### PR TITLE
2410.1 Retry update install

### PR DESCRIPTION
**Pull request by JonasKloseBW**
Sometimes, updates have to be installed multiple times to be applied successfully.

This pull request fixes error messages like these:
**.msu was not added because the specified Windows image or package has pending online actions.**

The Add-WindowsPackage function is tried up to 3 times now so that updates are hopefully applied correctly.

### CODE REVIEW

**Comment by JonasKloseBW** [comment]
Testing complete.
No issues remaining.

**Comment by JonasKloseBW** [comment]
Merged current 2410.1 into pull request

**Comment by rbalsleyMSFT** [comment]
With the changes I've pushed to 2410.1, can you retry with that? I haven't seen any issues with the pending changes. I also removed the pending switch as I don't believe that switch is necessary and have never had issues with it (it was included in someone elses commit awhile ago - if people are seeing issues with pending changes causing issues, I'd like to investigate further with DISM and/or CBS or other logs).

**Comment by JonasKloseBW** [comment]
There are still cases when retrying the update install seems to be necessary.
But sometimes this is triggered and sometimes it isn't.

**Review by rbalsleyMSFT — COMMENTED** [review]
Are you still seeing this issue where a retry is necessary? It's been about 2 months since I've pushed the changes to remove the preventpending switch and haven't seen any issues with retry failures or any issues in general. Do you still see failures and a retry is necessary?

**Pull request closed without merging**
