### PR TITLE
Copy Prefixes.txt to DeploymentDrive unattend folder

### PR DESCRIPTION
**Pull request by HedgeComp**
Created a Check to see if any of the unattend_xx.xml or Prefixes.txt files 
exist. If not, will writelog that the files are not found, and script continues. Currently throwing an error to console.

In the Latest Youtube Walkthrough section [Device Naming](https://www.youtube.com/watch?v=rqXRbgeeKSQ&t=4401s)
Slide states 

> -$CopyUnatted: $true will copy the files to the deploy partition of USB drive.

This is may be confusing, as it currently only copies and renames the unattend XML for your architecture. Not the _"prefixes.txt"_

Propose the following change to $CopyUnatted block to add logic to check if Prefixes.txt is found and then copy to the deploy partition of USB drive in the unattend folder. No need to remember to go back and manually copy prefixes.txt file over from your computer to the USB drive before imaging.  (Ermm.. Not that its every happened to me. I'm simply asking for a friend :flushed: )

@rbalsleyMSFT could consider renaming the initial Prefixes.txt in the repository to Prefixes_Sample.txt
to be consistent with the Applist_Sample.json. The assumption here is that if you have made changes to the file, you want to use it to cut down on the number of reboots and reduce app packages, as per your YouTube presentations.

### CODE REVIEW

**Comment by rbalsleyMSFT** [comment]
It's not expected that you'd have to manually copy the prefixes.txt. It should be copying the whole unattend folder. I see what happened. When I refactored the code for ARM64 support, I only did the XML file, not the prefixes.txt.

**Comment by HedgeComp** [comment]
Hi Richard,

yes, I saw that the original code was commented out for a full copy of the unattend folder before you had the different architecture. 

I like the idea of doing the pre-checks before you are 20 mins in the build only to discover the error and crash or not copy it in.

I would suggest that you still have the checks look for the prefixes.txt as the file renamed from the sample.txt. This way it will check and only copy if intend to be used.

Thus setting the standard for the default build example files going forward. Easier to understand and easier for you 

Please let me know if you want me to Close this Pull request or if you can re-assign my code else where I 'll leave it up.

Cheers

Scott

**Comment by HedgeComp** [comment]
See you have added the XML verification and the prefixes.txt check. CLosing Pull

**Comment by HedgeComp** [comment]
See you have added the XML verification and the prefixes.txt check. CLosing Pull

**Comment by rbalsleyMSFT** [comment]
There's currently an issue with it that I'll fix today, but yeah, it's gonna be fixed when I push 2409 to main.

Thanks,
Richard
________________________________

**Pull request closed without merging**
