### PR TITLE
Automated Win32 and Store App Downloads and Installs

### PR DESCRIPTION
**Pull request by zehadialam**
## Summary

This pull request provides an implementation of the features proposed in Issue [#30](https://github.com/rbalsleyMSFT/FFU/issues/30). It introduces functionality that leverages WinGet to automate the download of user-specified apps for inclusion in the FFU. The silent install commands for win32 apps are automatically added to the InstallAppsandSysprep.cmd file. Apps can be specified by the user in the AppsList.txt file under `C:\FFUDevelopment\Apps`. Win32 and Microsoft Store apps are supported for inclusion and must be distinguished by prefacing the app name with `win32:` or `store:`

**Example**
```txt
win32:7-Zip
store:Company Portal
```

To ensure that only a single result is received for the download to occur seamlessly, the `--exact` parameter is specified in WinGet’s `download` command for each app. Thus, app names must be specified exactly as their name is listed in the WinGet repository (case-sensitive). This is determined by typing in `winget search appname` and looking at the Name column to see how the app is listed.
```txt
PS C:\Windows\system32> winget search 7zip
Name              Id                     Version            Match         Source
--------------------------------------------------------------------------------
7-Zip             7zip.7zip              24.07              Moniker: 7zip winget
```

### `Install-WinGet`
This function installs the latest preview version of WinGet, since the preview version supports an experimental feature that allows the download of Microsoft Store apps. 

### `New-WinGetSettings`
This function creates a settings.json file that enables the storeDownload feature if it is not already enabled.

### `Get-Win32App`
This function searches the WinGet repository for a user-specified win32 app from the AppsList.txt file and downloads it to `C:\FFUDevelopment\Apps\Win32\Appname`. The Win32 and Appname directories are created by the function. It then constructs the silent install command for each app by extracting the silent install switches from the yaml file that is downloaded along with the msi or exe. After constructing the silent install command, the command is appended to the InstallAppsandSysprep.cmd file

### `Get-StoreApp`
This function searches the WinGet repository for a user-specified msstore app from the AppsList.txt file and downloads it to `C:\FFUDevelopment\Apps\MSStore\Appname`. The MSStore and Appname directories are created by the function. Not all store app downloads are currently supported by WinGet. Some of the non-in-box apps that can be downloaded include Company Portal, Power BI Desktop, and Remote Desktop.

### `Get-Apps`
This function retrieves the content from the AppList.txt file and populates either a win32 or storeapps array with the names of the apps. It verifies the installation of the preview version of WinGet and installs it if necessary. It then invokes either the `Get-Win32App` or `Get-StoreApp` function based on the contents of the win32 or storeapps array.

## Other Additions
- The InstallAppsandSysprep.cmd file includes code to provision every app package under the `C:\FFUDevelopment\Apps\MSStore` directory, so that they will install for all new users. The execution of this code is controlled by the INSTALL_STOREAPPS flag, which is set to "false" by default. If store apps are specified in the AppsList.txt file and they can successfully download, then the flag will be set to "true" by the `Get-StoreApp` function.

- Added code to clean up the Win32 and MSStore directories after the script finishes or if the dirty.txt file is detected.

- Modified the `Clear-InstallAppsandSysprep` function to include code that removes the silent install commands for win32 apps downloaded by WinGet and sets the INSTALL_STOREAPPS flag to "false".

## Log
log

### CODE REVIEW

**Comment by rbalsleyMSFT** [comment]
Merged. I'll start testing today.

**Comment by rbalsleyMSFT** [comment]
Had to add architecture filtering for msstore apps as Company Portal failed to install without it. I did the same for win32 apps, though it's probably not needed. I also made some minor changes to not remove the license and yaml files when the script tries to remove older versions of apps that it downloaded. I know you're skipping the license when provisioning the apps, which seems to be working fine, but at some point we may need the license files. 

Company Portal and 7-Zip both installed fine as expected on ARM. I'll test x64 later, but don't think there'll be any issues with that if ARM is working fine.

**Comment by zehadialam** [comment]
Ah, that's good to know. I noticed that including the architecture for some apps resulted in no results being found, unless `--architecture neutral` was specified. The Remote Desktop store app is like that.

Regarding the license file for apps, I always received an error during the license download for all the apps I tried. Does it download for you? I preferred to not skip the license, since the docs don't encourage it.

error

**Comment by rbalsleyMSFT** [comment]
Yeah, I get the licenses. I didn't get them last week when I was testing on another machine (x64 machine Entra ID joined to the MSFT tenant). On my ARM device it's not Entra ID joined. Not sure why it's working on this ARM machine.

image

But I do see the issue with Microsoft Remote Desktop. When I pass `--architecture arm64` it doesn't find it. But if I pass `--architecture neutral` it brings up the sign in window, but it doesn't find a package. If I don't pass the architecture parameter at all, it downloads fine. When looking at the yaml file, it shows architecture as neutral. 

So I think we need to attempt to use the value in $WindowsArch first, and if it doesn't find it, remove the architecture type. Let me know if you want to handle that, otherwise I'll modify the code to account for it.

**Comment by zehadialam** [comment]
Sounds good, I just submitted a PR with that adjustment.

**Pull request merged**
